=== uo288524/sew/EscritorioVirtual/xml/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (nombreRuta,tipoRuta,medioTransporte,tiempoDuracion,agenciaGestion,descripcionRuta,personasAdecuadas,lugarInicioRuta,direccionInicioRuta,coordenadasGeograficasRuta,referencias,recomendacionRuta,hitosRuta)>
<!ELEMENT nombreRuta (#PCDATA)> 
<!ELEMENT tipoRuta (#PCDATA)> 
<!ELEMENT medioTransporte (#PCDATA)> 
<!ELEMENT tiempoDuracion (#PCDATA)> 
<!ELEMENT agenciaGestion (#PCDATA)> 
<!ELEMENT descripcionRuta (#PCDATA)> 
<!ELEMENT personasAdecuadas (#PCDATA)> 
<!ELEMENT lugarInicioRuta (#PCDATA)> 
<!ELEMENT direccionInicioRuta (#PCDATA)> 
<!ELEMENT coordenadasGeograficasRuta (longitudR,latitudR,altitudR)> 
<!ELEMENT longitudR (#PCDATA)> 
<!ELEMENT latitudR (#PCDATA)> 
<!ELEMENT altitudR (#PCDATA)> 
<!ELEMENT referencias (referencia+)> 
<!ELEMENT referencia (#PCDATA)> 
<!ELEMENT recomendacionRuta (#PCDATA)> 
<!ELEMENT hitosRuta (hito+)> 
<!ELEMENT hito (nombreHito,descripcionHito,coordenadasGeograficasHito,distanciaAnterior,galeriaFotos,galeriaVideos)> 
<!ELEMENT nombreHito (#PCDATA)> 
<!ELEMENT descripcionHito (#PCDATA)> 
<!ELEMENT coordenadasGeograficasHito (longitudH,latitudH,altitudH)> 
<!ELEMENT longitudH (#PCDATA)> 
<!ELEMENT latitudH (#PCDATA)> 
<!ELEMENT altitudH (#PCDATA)> 
<!ELEMENT distanciaAnterior (#PCDATA)> 
<!ELEMENT galeriaFotos (foto+)> 
<!ELEMENT foto (#PCDATA)> 
<!ELEMENT galeriaVideos (video*)> 
<!ELEMENT video (#PCDATA)> 
<!ATTLIST ruta fechaInicio CDATA #IMPLIED>
<!ATTLIST ruta horaInicio CDATA #IMPLIED>

=== uo288524/sew/EscritorioVirtual/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
    <ruta fechaInicio="14 de marzo" >
        <nombreRuta>El universo de las tribus ancestrales</nombreRuta>
        <tipoRuta>Cultural</tipoRuta>
        <medioTransporte>Vehículo todoterreno</medioTransporte>
        <tiempoDuracion>12 días</tiempoDuracion>
        <agenciaGestion>Banoa</agenciaGestion>
        <descripcionRuta>Este es un viaje de gran impacto, tanto desde 
            un prisma visual como, a buen seguro, en lo más íntimo
             de nuestras emociones. Las costumbres y ritos que vamos
             a presenciar en cada una de las aldeas que
              visitaremos no nos dejarán indiferentes</descripcionRuta>
        <personasAdecuadas> todas las edades</personasAdecuadas>
        <lugarInicioRuta>Yuba</lugarInicioRuta>
        <direccionInicioRuta>Aeropuerto Internacional de Yuba</direccionInicioRuta>
        <coordenadasGeograficasRuta >   
            <longitudR>31°36'O7 E</longitudR> 
            <latitudR>4°52'16 N</latitudR>
            <altitudR>460m</altitudR>
        </coordenadasGeograficasRuta>
        <referencias>
            <referencia>https://www.banoa.com/viaje/sudan-del-sur-el-universo-de-las-tribus-ancestrales/727</referencia>
            <referencia>https://www.gettyimages.es/fotos/terekeka</referencia>
            <referencia>https://es.wikipedia.org/wiki/Etnias_de_Sud%C3%A1n_del_Sur</referencia>
        </referencias>
        <recomendacionRuta>10</recomendacionRuta>
        <hitosRuta>
            <hito>
                <nombreHito>Terekeka</nombreHito>
                <descripcionHito>El universo de los Mundari</descripcionHito>
                <coordenadasGeograficasHito >
                    <longitudH>31°45'28 E</longitudH> 
                    <latitudH>5°26'28 N</latitudH>
                    <altitudH>488m</altitudH>
                </coordenadasGeograficasHito>
                <distanciaAnterior>65.833,45 m</distanciaAnterior>
                <galeriaFotos>
                    <foto>multimedia/imagenes/Terekeka.jpg</foto>
                </galeriaFotos>
                <galeriaVideos></galeriaVideos>
            </hito>
            <hito>
                <nombreHito>Kapoeta</nombreHito>
                <descripcionHito>Tierra de las tribus Toposas</descripcionHito>
                <coordenadasGeograficasHito>
                    <longitudH>33°35'3 E</longitudH> 
                    <latitudH>4°46'23 N</latitudH>
                    <altitudH>667m</altitudH>
                </coordenadasGeograficasHito>
                <distanciaAnterior>219.505,67 m</distanciaAnterior>
                <galeriaFotos>
                    <foto>multimedia/imagenes/Kapoeta.jpg</foto>
                </galeriaFotos>
                <galeriaVideos></galeriaVideos>
            </hito>
            <hito>
                <nombreHito>Kimatong</nombreHito>
                <descripcionHito>Pieles escarificadas y labios perforados en aldeas remotas</descripcionHito>
                <coordenadasGeograficasHito >
                    <longitudH>33°15'48E</longitudH> 
                    <latitudH>4°41'00 N</latitudH>
                    <altitudH>643 m</altitudH>
                </coordenadasGeograficasHito>
                <distanciaAnterior>37.894,52 m</distanciaAnterior>
                <galeriaFotos>
                    <foto>multimedia/imagenes/Kimatong.jpg</foto>
                </galeriaFotos>
                <galeriaVideos></galeriaVideos>
            </hito>
        </hitosRuta>


    </ruta>
     <ruta fechaInicio="01 de diciembre">
        <nombreRuta>Tribu dinka y reinos de las montañas Lafit</nombreRuta>
        <tipoRuta>Viaje etnográfico</tipoRuta>
        <medioTransporte>Vehículo todoterreno</medioTransporte>
        <tiempoDuracion>9 días</tiempoDuracion>
        <agenciaGestion>Last Places</agenciaGestion>
        <descripcionRuta>Iremos hasta el reino de la tribu lotuko,
             cerca del pueblo de Torit. Uno y otro tienen reyes que, entre sus funciones,
              tienen el deber de invocar la lluvia. También, presentan una organización
               social basada en los grupos de edad.</descripcionRuta>
        <personasAdecuadas> todas las edades</personasAdecuadas>
        <lugarInicioRuta>Yuba</lugarInicioRuta>
        <direccionInicioRuta>Aeropuerto Internacional de Yuba</direccionInicioRuta>
        <coordenadasGeograficasRuta >    
            <longitudR>31°36'O7 E</longitudR> 
            <latitudR>4°52'16 N</latitudR>
            <altitudR>460m</altitudR>
        </coordenadasGeograficasRuta>
        <referencias>
            <referencia>https://lastplaces.com/viajar/viaje-etnografico-sudan-sur-tribus-diciembre-23/</referencia>
            <referencia>https://earth.google.com/web</referencia>
            <referencia>https://es.wikipedia.org/wiki/Etnias_de_Sud%C3%A1n_del_Sur</referencia>
        </referencias>
        <recomendacionRuta>9.8</recomendacionRuta>
        <hitosRuta>
            <hito>
                <nombreHito>Munduri Cattle Camp</nombreHito>
                <descripcionHito>el territorio pantanoso a lo largo del Nilo Blanco</descripcionHito>
                <coordenadasGeograficasHito >
                    <longitudH>31°00'49 E</longitudH> 
                    <latitudH>6°58'07 N</latitudH>
                    <altitudH>409m</altitudH>
                </coordenadasGeograficasHito>
                <distanciaAnterior>240.365,05 m</distanciaAnterior>
                <galeriaFotos>
                    <foto>multimedia/imagenes/Munduri.jfif</foto>
                </galeriaFotos>
                <galeriaVideos></galeriaVideos>
            </hito>
            <hito>
                <nombreHito>Torit</nombreHito>
                <descripcionHito>Tribu lotuko</descripcionHito>
                <coordenadasGeograficasHito >
                    <longitudH>32°27'20 E</longitudH> 
                    <latitudH>4°24'47 N</latitudH>
                    <altitudH>586m</altitudH>
                </coordenadasGeograficasHito>
                <distanciaAnterior>322.133,4 m</distanciaAnterior>
                <galeriaFotos>
                    <foto>multimedia/imagenes/torit.jpg</foto>
                </galeriaFotos>
                <galeriaVideos></galeriaVideos>
            </hito>
            <hito>
                <nombreHito>Lafit Mountains</nombreHito>
                <descripcionHito>el reino de los lopits, en una remota y hermosa zona montañosa</descripcionHito>
                <coordenadasGeograficasHito >
                    <longitudH>32°42'22 E</longitudH> 
                    <latitudH>4°42'31 N</latitudH>
                    <altitudH>661m</altitudH>
                </coordenadasGeograficasHito>
                <distanciaAnterior>31.125,08 m</distanciaAnterior>
                <galeriaFotos>
                    <foto>multimedia/imagenes/LafitMountains.jpg</foto>
                </galeriaFotos>
                <galeriaVideos></galeriaVideos>
            </hito>
           
        </hitosRuta>


    </ruta>
    <ruta fechaInicio="10 de febrero" >
        <nombreRuta>Viaje Fotográfico Sudán del Sur</nombreRuta>
        <tipoRuta>Fotográfica</tipoRuta>
        <medioTransporte>Vechículo Todoterreno</medioTransporte>
        <tiempoDuracion>13 días</tiempoDuracion>
        <agenciaGestion>PhotoTravel</agenciaGestion>
        <descripcionRuta>En esta edición PhotoTravel os ofrece una expedición irrepetible
             al corazón de Sudán del Sur, un país que alberga una riqueza etnográfica única.
              Un recorrido en el que visitaremos a algunas de las etnias mas
               impresionantes del mundo.</descripcionRuta>
        <personasAdecuadas> todas las edades</personasAdecuadas>
        <lugarInicioRuta>Yuba</lugarInicioRuta>
        <direccionInicioRuta>Aeropueto internacional de Yuba</direccionInicioRuta>
        <coordenadasGeograficasRuta >    
            <longitudR>31°36'O7 E</longitudR> 
            <latitudR>4°52'16 N</latitudR>
            <altitudR>460m</altitudR>
        </coordenadasGeograficasRuta>
        <referencias>
            <referencia>https://phototravel.es/tours/viaje-fotografico-sudan-del-sur/</referencia>
            <referencia>https://earth.google.com/web</referencia>
            <referencia>https://es.wikipedia.org/wiki/Etnias_de_Sud%C3%A1n_del_Sur</referencia>
        </referencias>
        <recomendacionRuta>9.5</recomendacionRuta>
        <hitosRuta>
            <hito>
                <nombreHito>Kapoeta</nombreHito>
                <descripcionHito>Tierra de los Boya</descripcionHito>
                <coordenadasGeograficasHito >
                    <longitudH>33°35'3 E</longitudH> 
                    <latitudH>4°46'23 N</latitudH>
                    <altitudH>667m</altitudH>
                </coordenadasGeograficasHito>
                <distanciaAnterior>223.364,49 m</distanciaAnterior>
                <galeriaFotos>
                    <foto>multimedia/imagenes/Kapoeta.jpg</foto>
                </galeriaFotos>
                <galeriaVideos></galeriaVideos>
            </hito>
            <hito>
                <nombreHito>Torit</nombreHito>
                <descripcionHito>Tribu Lopit al este de torit</descripcionHito>
                <coordenadasGeograficasHito >
                    <longitudH>32°27'20 E</longitudH> 
                    <latitudH>4°24'47 N</latitudH>
                    <altitudH>586m</altitudH>
                </coordenadasGeograficasHito>
                <distanciaAnterior>122.946,45 m</distanciaAnterior>
                <galeriaFotos>
                    <foto>multimedia/imagenes/torit.jpg</foto>
                </galeriaFotos>
                <galeriaVideos></galeriaVideos>
